# Generated by Django 4.2.5 on 2023-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keys_users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_name", models.CharField(max_length=100)),
                ("key_public", models.CharField(max_length=200)),
                ("key_private", models.CharField(max_length=200)),
            ],
        ),
    ]
