# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inicio_sesion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Archivos_ui_en_py.Estilos_o_diseños import Estilos
from Archivos_ui_en_py.Registro import Registro
#importar las funciones que estan dentro del archivo Funcion_cierre.py que a su vez esta dentro de la carpeta Funciones


class Inicio_sesion(object):
    def setupUi(self, MainWindow):
        #MainWindow es la ventana principal
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(311, 386)
        #MainWindow.setMaximumSize(900, 600)#Determenia el tamaño maximo de la ventana
        
        #centralwidget es el que contiene el Frame_fondo
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        #spacerItems son los que mantienen el espacio entre los elementos
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem7 = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem9 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        #Frame_fondo es el que contiene el Frame_ecapsulador y este siendo el frame principal
        self.Frame_fondo = QtWidgets.QFrame(self.centralwidget)
        self.Frame_fondo.setLayoutDirection(QtCore.Qt.LeftToRight) # type: ignore
        self.Frame_fondo.setStyleSheet(Estilos.Estilo_Frame_Fondo(self)) # type: ignore
        self.Frame_fondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_fondo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Frame_fondo.setObjectName("Frame_fondo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Frame_fondo)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        #Frame_ecapsulador es el que contiene el Frame_componentes
        self.Frame_ecapsulador = QtWidgets.QFrame(self.Frame_fondo)
        self.Frame_ecapsulador.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_ecapsulador.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_ecapsulador.setObjectName("Frame_ecapsulador")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Frame_ecapsulador)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.addItem(spacerItem)

        #Contenedor_vertical es el que contiene el Frame_componentes
        self.Contenedor_vertical = QtWidgets.QVBoxLayout()
        self.Contenedor_vertical.setObjectName("Contenedor_vertical")
        self.Contenedor_vertical.addItem(spacerItem1)

        #Frame_componentes es el que contiene los elementos de la ventana
        self.Frame_componentes = QtWidgets.QFrame(self.Frame_ecapsulador)
        self.Frame_componentes.setMaximumSize(QtCore.QSize(400, 600)) #Determenia el tamaño maximo del frame
        self.Frame_componentes.setStyleSheet(Estilos.Estilo_Boton_Inicio_Sesion(self)+Estilos.Estilo_Label(self)) # type: ignore
        self.Frame_componentes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_componentes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_componentes.setObjectName("Frame_componentes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Frame_componentes)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        #Label que contiene el nombre del programa
        self.Nombre_encabezado = QtWidgets.QLabel(self.Frame_componentes)
        self.Nombre_encabezado.setMaximumSize(QtCore.QSize(16777215, 50)) #Determina el tamaño maximo del label
        self.Nombre_encabezado.setAlignment(QtCore.Qt.AlignCenter) # type: ignore
        self.Nombre_encabezado.setObjectName("Nombre_encabezado")
        self.verticalLayout_3.addWidget(self.Nombre_encabezado)
        self.verticalLayout_3.addItem(spacerItem2)

        #Label que contiene el texto=usuario
        self.Label_usuario = QtWidgets.QLabel(self.Frame_componentes)
        self.Label_usuario.setObjectName("Label_usuario")
        self.verticalLayout_3.addWidget(self.Label_usuario)

        #Textbox que contiene el nombre del usuario
        self.Text_usuario = QtWidgets.QLineEdit(self.Frame_componentes)
        self.Text_usuario.setStyleSheet(Estilos.Estilo_Textbox_Usuario(self)) # type: ignore
        self.Text_usuario.setObjectName("Text_usuario")
        self.verticalLayout_3.addWidget(self.Text_usuario)
        self.verticalLayout_3.addItem(spacerItem3)

        #Label que contiene el texto=contraseña
        self.Label_password = QtWidgets.QLabel(self.Frame_componentes)
        self.Label_password.setObjectName("Label_password")
        self.verticalLayout_3.addWidget(self.Label_password)

        #Textbox que contiene la contraseña
        self.Text_password = QtWidgets.QLineEdit(self.Frame_componentes)
        self.Text_password.setStyleSheet(Estilos.Estilo_Textbox_Contraseña(self)) # type: ignore
        self.Text_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Text_password.setObjectName("Text_password")
        self.verticalLayout_3.addWidget(self.Text_password)
        self.verticalLayout_3.addItem(spacerItem4)

        #Boton para iniciar sesion
        self.Button_inicio_sesion = QtWidgets.QPushButton(self.Frame_componentes)
        self.Button_inicio_sesion.setObjectName("Button_inicio_sesion")
        self.verticalLayout_3.addWidget(self.Button_inicio_sesion)        
        self.verticalLayout_3.addItem(spacerItem5)

        #Checkbox para mantener la sesion iniciada
        self.Mantener_sesion = QtWidgets.QCheckBox(self.Frame_componentes)
        self.Mantener_sesion.setStyleSheet(Estilos.Estilo_Checkbox_Manter_Sesion(self)) # type: ignore
        self.Mantener_sesion.setObjectName("Mantener_sesion")
        self.verticalLayout_3.addWidget(self.Mantener_sesion)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        #Label que contiene el texto=¿No tienes cuenta?
        self.Label_pregunta = QtWidgets.QLabel(self.Frame_componentes)
        self.Label_pregunta.setObjectName("Label_pregunta")
        self.horizontalLayout.addWidget(self.Label_pregunta)

        #Boton para registrarse
        self.Button_registrarse = QtWidgets.QPushButton(self.Frame_componentes)
        self.Button_registrarse.setObjectName("Button_registrarse")
        self.horizontalLayout.addWidget(self.Button_registrarse)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        #Agrega el Frame_componentes al Contenedor_vertical
        self.Contenedor_vertical.addWidget(self.Frame_componentes)
        self.Contenedor_vertical.addItem(spacerItem8)
        self.horizontalLayout_2.addLayout(self.Contenedor_vertical)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_3.addWidget(self.Frame_ecapsulador)
        self.horizontalLayout_4.addWidget(self.Frame_fondo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Funcion que se ejecuta al presionar el boton de iniciar sesion
        self.Button_inicio_sesion.clicked.connect(self.datos_user)
        self.Button_registrarse.clicked.connect(self.registrarse)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        #Cambia el texto de los elementos de la ventana
        MainWindow.setWindowTitle(_translate("MainWindow", "Encriptador"))
        self.Nombre_encabezado.setText(_translate("MainWindow", "Encriptador"))
        self.Label_usuario.setText(_translate("MainWindow", "Usuario"))
        self.Label_password.setText(_translate("MainWindow", "Contraseña"))
        self.Button_inicio_sesion.setText(_translate("MainWindow", "Iniciar sesión"))
        self.Mantener_sesion.setText(_translate("MainWindow", "Mantener sesión iniciada"))
        self.Label_pregunta.setText(_translate("MainWindow", "No tienes cuenta"))
        self.Button_registrarse.setText(_translate("MainWindow", "Registrate"))
    
    #Funcion que obtiene los datos del usuario
    def datos_user(self):
        self.user = self.Text_usuario.text()
        self.password = self.Text_password.text()
        print(self.user)
        print(self.password)

    #Funcion que abre la ventana de registro y cierra la ventana de inicio de sesion
    def registrarse(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Registro()
        self.ui.setupUi(self.window)
        self.window.show()
        


        
        

        







