# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Fuciones.Estilos_o_diseños import Estilos


class Registro(object):
    def setupUi(self, Registro):
        #Registro es la ventana principal
        Registro.setObjectName("Registro")
        Registro.resize(311, 386)
        Registro.setStyleSheet("background-image: url(src/imagenes/Fondo.svg);\n"
                                "background-repeat: no-repeat;\n"
                                "background-size: cover;\n"
                                "background-position: center;\n")

        #centralwidget es el que contiene al Frame_fondo
        self.centralwidget = QtWidgets.QWidget(Registro)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0) #Prueba
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        #spacerItems son los que mantienen el espacio entre los elementos
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem2 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem3 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem4 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spacerItem7 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(spacerItem)

        #Frame_fondo es el que contiene al Frame_ecapsulador
        self.Frame_fondo = QtWidgets.QFrame(self.centralwidget)
        self.Frame_fondo.setLayoutDirection(QtCore.Qt.LeftToRight) # type: ignore
        self.Frame_fondo.setStyleSheet(Estilos.Estilo_Frame_Fondo(self)) #type: ignore
        self.Frame_fondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_fondo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Frame_fondo.setObjectName("Frame_fondo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Frame_fondo)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        #Frame_ecapsulador es el que contiene al Frame_componentes
        self.Frame_ecapsulador = QtWidgets.QFrame(self.Frame_fondo)
        self.Frame_ecapsulador.setMaximumSize(QtCore.QSize(400, 600))
        self.Frame_ecapsulador.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_ecapsulador.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_ecapsulador.setObjectName("Frame_ecapsulador")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Frame_ecapsulador)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        #verticalLayout_3 es el que contiene al Frame_componentes
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.addItem(spacerItem1)

        #Frame_componentes es el que contiene a todos los elementos
        self.Frame_componentes = QtWidgets.QFrame(self.Frame_ecapsulador)
        self.Frame_componentes.setMaximumSize(QtCore.QSize(400, 600))
        self.Frame_componentes.setStyleSheet(Estilos.Estilo_Boton_Inicio_Sesion(self)+Estilos.Estilo_Label(self)+Estilos.Estilo_Textbox_Usuario(self)+Estilos.Estilo_Textbox_Contraseña(self)) #type: ignore
        self.Frame_componentes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_componentes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_componentes.setObjectName("Frame_componentes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Frame_componentes)
        self.verticalLayout.setObjectName("verticalLayout")

        #Label que contiene el nombre de la aplicación
        self.Label_Registro_cuenta = QtWidgets.QLabel(self.Frame_componentes)
        self.Label_Registro_cuenta.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Label_Registro_cuenta.setAlignment(QtCore.Qt.AlignCenter) #type: ignore
        self.Label_Registro_cuenta.setObjectName("Label_Registro_cuenta")
        self.verticalLayout.addWidget(self.Label_Registro_cuenta)
        self.verticalLayout.addItem(spacerItem2)

        #Label que contiene el texto "Usuario"
        self.Label_Usuario = QtWidgets.QLabel(self.Frame_componentes)
        self.Label_Usuario.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Label_Usuario.setObjectName("Label_Usuario")
        self.verticalLayout.addWidget(self.Label_Usuario)

        #Textbox que contiene el nombre de usuario
        self.Textbox_usuario = QtWidgets.QLineEdit(self.Frame_componentes)
        self.Textbox_usuario.setObjectName("Textbox_usuario")
        self.verticalLayout.addWidget(self.Textbox_usuario)
        self.verticalLayout.addItem(spacerItem3)

        #Label que contiene el texto "Contraseña"
        self.Label_password = QtWidgets.QLabel(self.Frame_componentes)
        self.Label_password.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Label_password.setObjectName("Label_password")
        self.verticalLayout.addWidget(self.Label_password)

        #Textbox que contiene la contraseña
        self.Textbox_password = QtWidgets.QLineEdit(self.Frame_componentes)
        self.Textbox_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Textbox_password.setObjectName("Textbox_password")
        self.verticalLayout.addWidget(self.Textbox_password)
        self.verticalLayout.addItem(spacerItem4)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        #Botón que permite cancelar el registro
        self.Button_cancelar = QtWidgets.QPushButton(self.Frame_componentes)
        self.Button_cancelar.setObjectName("Button_cancelar")
        self.horizontalLayout.addWidget(self.Button_cancelar)
        self.horizontalLayout.addItem(spacerItem5)

        #Botón que permite registrar el usuario
        self.Button_registro = QtWidgets.QPushButton(self.Frame_componentes)
        self.Button_registro.setObjectName("Button_registro")
        self.horizontalLayout.addWidget(self.Button_registro)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.Frame_componentes)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addWidget(self.Frame_ecapsulador)
        self.horizontalLayout_4.addWidget(self.Frame_fondo)
        self.horizontalLayout_4.addItem(spacerItem7)
        Registro.setCentralWidget(self.centralwidget)

        self.retranslateUi(Registro)
        QtCore.QMetaObject.connectSlotsByName(Registro)

    def retranslateUi(self, Registro):
        _translate = QtCore.QCoreApplication.translate
        Registro.setWindowTitle(_translate("Registro", "MainWindow"))
        self.Label_Registro_cuenta.setText(_translate("Registro", "Registro de cuenta"))
        self.Label_Usuario.setText(_translate("Registro", "Usuario"))
        self.Label_password.setText(_translate("Registro", "Contraseña"))
        self.Button_cancelar.setText(_translate("Registro", "Cancelar"))
        self.Button_registro.setText(_translate("Registro", "Registrarse"))
