# Generated by Django 4.2.5 on 2023-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users_EncrytedPage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users_encrytedpage",
            name="master_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
