# Generated by Django 4.2.5 on 2023-10-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users_EncrytedPage", "0002_users_encrytedpage_master_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users_encrytedpage",
            name="master_key",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
