# Generated by Django 4.2.5 on 2023-09-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Users_EncrytedPage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="passwords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origen", models.CharField(max_length=200)),
                ("user_name", models.CharField(max_length=200)),
                ("correo_electronico", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users_EncrytedPage.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="keys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(max_length=200)),
                ("private_key", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users_EncrytedPage.users",
                    ),
                ),
            ],
        ),
    ]
