# Generated by Django 4.2.5 on 2023-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users_EncrytedPage", "0002_passwords_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="keys",
            name="name_key",
            field=models.CharField(default="key", max_length=200),
        ),
    ]
