# Generated by Django 4.2.5 on 2023-09-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users_EncrytedPage", "0003_keys_name_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.EmailField(max_length=200),
        ),
    ]
