# Generated by Django 4.2.5 on 2023-09-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users_EncrytedPage", "0004_alter_users_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwords",
            name="correo_electronico",
            field=models.EmailField(max_length=200),
        ),
    ]
