# Generated by Django 4.2.5 on 2023-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users_EncrytedPage", "0005_alter_passwords_correo_electronico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
